// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package com.gbabler.msusers.grpc;

public interface WeatherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeatherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string state = 1;</code>
   * @return The state.
   */
  String getState();
  /**
   * <code>string state = 1;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();
}
