// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package com.gbabler.msusers.grpc;

public interface WeatherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeatherRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city = 1;</code>
   * @return The city.
   */
  String getCity();
  /**
   * <code>string city = 1;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
